# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jay
email: jaywalnut310@gmail.com
description: AI & Deep Learning Enthusiast
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaywalnut310.github.io" # the base hostname & protocol for your site
github_username:  jaywalnut310
linkedin_username: jaywalnut310
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
